name = "daemon"
main = "src/worker.ts"
compatibility_date = "2025-08-20"
workers_dev = true

# Custom domain route
routes = [
  { pattern = "daemon.danielmiessler.com", custom_domain = true }
]

[site]
bucket = "./dist"
